### PR TITLE
fix(mkdir): mitigate directory creation race condition

### LINKED ISSUE #1018: `mkdirSyncRecursive()` shouldn't fail when directory exists unexpectedly
When using `shx mkdir -p ...`, occasional, unnecessarily terminal, errors can occur if the target directory is created by another process during the execution of `mkdirSyncRecursive()`.

It's an obvious race condition that I've run into occasionally when using `shx` for builds with multiple parallel steps (eg, <https://github.com/rivy/js.xdg-portable/runs/1896221924?check_suite_focus=true>)

Ignoring 'EEXIST' errors in `mkdirSyncRecursive()` can mitigate this problem.

### PR DESCRIPTION
**Pull request by rivy**
Fixes #1018

### CODE REVIEW

**Comment by rivy** [comment]
Only previously created directories should be allowed/ignored, so I added an `isFile()` check to the catch logic.

**Comment by rivy** [comment]
This doesn't touch 'test', so I think the single AppVeyor failure is unrelated (and likely a random "cosmic-ray" failure).

File: src/mkdir.js [hunk 1]
```diff
@@ -28,8 +28,14 @@ function mkdirSyncRecursive(dir) {
   // Base dir does not exist, go recursive
   mkdirSyncRecursive(baseDir);
 
-  // Base dir created, can create dir
-  fs.mkdirSync(dir, parseInt('0777', 8));
+  try {
+    // Base dir created, can create dir
+    fs.mkdirSync(dir, parseInt('0777', 8));
```
Comment (nfischer) [inline src/mkdir.js:33]: It looks like this same bug can happen above on line 24 (the other call to `fs.mkdirSync`). What do you think about refactoring this to recurse first (if necessary) and only call `fs.mkdirSync` in one spot?

```js
// Replace lines 22-39 with...

// Base dir does not exist, recursion necessary
if (!fs.existsSync(baseDir)) {
  mkdirSyncRecursive(baseDir);
}

try {
  // Base dir created, can create dir
  // etc. ...
}
```

**Review by nfischer — CHANGES_REQUESTED** [review]

File: src/mkdir.js (hunk 1 above)
Comment (rivy) [reply src/mkdir.js:29]: Sure, I'll push a change as a "fixup! ..." commmit.
If it's corrent, tests ok, and you like it, I'll squash it into the initial commit prior to a merge.

Comment (rivy) [reply src/mkdir.js:29]: Tests are passing, commits are squashed.

File: src/mkdir.js [hunk 2]
```diff
@@ -19,17 +19,19 @@ function mkdirSyncRecursive(dir) {
...
+  }
 
-  // Base dir created, can create dir
-  fs.mkdirSync(dir, parseInt('0777', 8));
+  try {
+    // Base dir created, can create dir
+    fs.mkdirSync(dir, parseInt('0777', 8));
+  } catch (e) {
+    // swallow directory exists errors ('EEXIST'); mitigates race conditions
+    /* istanbul ignore next */
```
Comment (nfischer) [inline src/mkdir.js:32]: I think we can remove `istanbul ignore next` because this now handles the non-racy condition where base dir exists.

You could also update the comment since this isn't only for race conditions (it's just the non-racy way to create a directory if it doesn't already exist).

**Review by nfischer — CHANGES_REQUESTED** [review]
Looks good! I think we can remove the `istanbul ignore next` part, but this is great otherwise!

File: src/mkdir.js (hunk 2 above)
Comment (rivy) [reply src/mkdir.js]: Done.

Comment (nfischer) [reply src/mkdir.js]: It looks like this caught some missing test coverage 😄  I think we weren't testing the case where `mkdir -p` is called on a directory which already exists. I filed issue #1022 to track this.

**Review by nfischer — APPROVED** [review]
