### PR TITLE
fix(exec): now actually supports shell option

### LINKED ISSUE #138: shell builtin
stupid question: can I call shell-builtin ?
Im trying exec with history
getting:
'history' is not recognized as an internal or external command,
operable program or batch file.
Exit code: 1
Program output: 'history' is not recognized as an internal or external command,
operable program or batch file.

### PR DESCRIPTION
**Pull request by nfischer**
Looks like #335 doesn't work perfectly with all options. This is because `execSync` does 2 calls to `exec()`, and some options need to be passed to both calls.

This should clean things up a bit, and fix the issue for the `shell` option, which would actually fix #138 and #208.

### CODE REVIEW

File: src/exec.js [hunk 1]
```diff
@@ -65,11 +65,18 @@ function execSync(cmd, opts) {
   var execCommand = '"'+process.execPath+'" '+scriptFile;
   var script;
 
+  var optArray = [];
```
Comment (ariporad) [inline src/exec.js]: I feel like this should just be an object that we `JSON.stringify`.

Comment (nfischer) [inline src/exec.js]: That would probably be better. I'll look into that.

**Comment by nfischer** [comment]
@ariporad This should be good now

File: test/exec.js [hunk 2]
```diff
@@ -107,6 +107,31 @@ if (process.version >= 'v0.11') { // this option doesn't work on v0.10
   assert.ok(shell.error());
 }
 
+// check process.env works
+assert.ok(!shell.env.FOO);
+shell.env.FOO = 'Hello world';
+result = shell.exec('echo $FOO');
```
Comment (ariporad) [inline test/exec.js]: `cmd.exe` doesn't support variables prefixed with a `$`, what you want here is `%FOO%`.

**Comment by ariporad** [comment]
LGTM, except for AppVeyor, which is failing.

File: test/exec.js (hunk 2 above)
Comment (nfischer) [inline test/exec.js]: Thanks! Good catch

**Comment by nfischer** [comment]
@ariporad it should be working now

File: src/exec.js [hunk 3]
```diff
@@ -65,11 +65,14 @@ function execSync(cmd, opts) {
   var execCommand = '"'+process.execPath+'" '+scriptFile;
   var script;
 
+  opts.cwd = path.resolve(opts.cwd);
+  var optString = JSON.stringify(opts);
```
Comment (TimothyGu) [inline src/exec.js]: This isn't safe against Unicode newlines (namely, U+2028 and U+2029): http://stackoverflow.com/a/9168133/1937836

Something like https://www.npmjs.com/package/js-stringify should fix this issue
