### PR TITLE
Properly handle directories as arguments

### LINKED ISSUE #707: How am I suppose to handle errors with ShellJS?
**Node:** v7.9.0
**ShellJS:** 0.7.7
**OS:** Windows 10 (with Ubuntu Bash)

I'm trying to **cat** a directory (which should obviously fail) but I want to catch the error instead of exiting my program altogether but try/catch doesn't seem to work:

````js
function cat(path) {
  try {
    return shx.cat(path); // Completely exists the program when fails.
  } catch(e) {
    return "Error";
  }
}
````

Error on exit:

````
ShellJS: internal error
Error: EISDIR: illegal operation on a directory, read
    at Object.fs.readSync (fs.js:682:19)
    at tryReadSync (fs.js:480:20)
    at Object.fs.readFileSync (fs.js:517:19)
    at /mnt/d/nou/ContentAPI/node_modules/shelljs/src/cat.js:35:15
    at Array.forEach (native)
    at Object._cat (/mnt/d/nou/ContentAPI/node_modules/shelljs/src/cat.js:30:9)
    at Object.cat (/mnt/d/nou/ContentAPI/node_modules/shelljs/src/common.js:383:25)
    at cat (/mnt/d/nou/ContentAPI/ContentAPI.js:78:16)
    at Object.<anonymous> (/mnt/d/nou/ContentAPI/ContentAPI.js:27:24)
    at Generator.next (<anonymous>)
    at onFulfilled (/mnt/d/nou/ContentAPI/node_modules/co/index.js:65:19)
    at /mnt/d/nou/ContentAPI/node_modules/co/index.js:54:5
    at Object.co (/mnt/d/nou/ContentAPI/node_modules/co/index.js:50:10)
    at Object.toPromise (/mnt/d/nou/ContentAPI/node_modules/co/index.js:118:63)
    at next (/mnt/d/nou/ContentAPI/node_modules/co/index.js:99:29)
    at onFulfilled (/mnt/d/nou/ContentAPI/node_modules/co/index.js:69:7)
````

### PR DESCRIPTION
**Pull request by nfischer**
We previously did not handle directories very well for many of our commands (would immediately error out). This fixes that.

 * `cat()`: did not handle directories as inputs, now it gracefully errors
 * `head()`: same thing. It also had a typo in a test.
 * `sort()`: same thing. It had the same typo.
 * `tail()`: same bug, and same typo.
 * `uniq()`: did not handle directories as inputs. Did not handle directories as outputs. Did not handle non-existent inputs (this slipped through because of a test typo). All are treated as errors.

Fixes #707

### CODE REVIEW

File: src/head.js [hunk 1]
```diff
@@ -72,9 +72,16 @@ function _head(options, files) {
 
   var shouldAppendNewline = false;
   files.forEach(function (file) {
-    if (!fs.existsSync(file) && file !== '-') {
-      common.error('no such file or directory: ' + file, { continue: true });
-      return;
+    if (file !== '-') {
+      if (!fs.existsSync(file)) {
+        common.error('no such file or directory: ' + file, { continue: true });
+        return;
```
Comment (nfischer) [inline src/head.js]: It doesn't throw an error with `continue: true`

**Comment by nfischer** [comment]
@freitagbr PTAL

**Comment by freitagbr** [comment]
LGTM
