### PR TITLE
Fix tests on Windows

### LINKED ISSUE #294: run-tests.js is broken for cmd.exe
I was trying out `run-tests.js` on my Windows machine, and ran into *lots* of problems. Since we're trying to get good support for Windows, I figured I'd make this a formal issue so that others can chime in and confirm the behavior I'm seeing.

The end-goal of this issue is to open up `cmd.exe` on Windows, `cd` to the shelljs directory, type `npm test`, and see that all the tests pass. To me this seems like a worthy goal.

With that said, if someone else sees behavior different from what I'm seeing, please verify that you're running everything through `cmd.exe`, like I am. I already know this can run on some other shells (Bash, for instance), but I'd like to see this work on this particular shell.

Initial problems I've seen:

 - must use `node path/to/jshint` in the `run-tests` script, instead of relying on the shebang
 - must expand wildcards ourselves, not relying on the shell, since [cmd relies on the application to expand them](https://superuser.com/questions/460598/is-there-any-way-to-get-the-windows-cmd-shell-to-expand-wildcard-paths), and jshint doesn't appear to be doing this
 - `exec()` will start in the current working directory if run through `cmd.exe`. If we pass the `cwd` argument to `child_process.exec()`, then this will fix the issue only for admin mode (not regular user mode). I think this is only possible to fix for admin mode. This means that all our exec calls will need `pwd()` prefixed to the paths.

I'll add more to the list in comments as I find the issues.

### PR DESCRIPTION
**Pull request by BYK**
Fixes #294 partially and #296.

### CODE REVIEW

File: src/ln.js [hunk 1]
```diff
@@ -47,7 +47,7 @@ function _ln(options, source, dest) {
   if (options.symlink) {
     fs.symlinkSync(source, dest, os.platform() === "win32" ? "junction" : null);
   } else {
-    fs.linkSync(source, dest, os.platform() === "win32" ? "junction" : null);
+    fs.linkSync(source, dest);
```
Comment (BYK) [inline src/ln.js]: This was a bug since the last option doesn't exist in `linkSync` at all.

File: src/ln.js [hunk 2]
```diff
@@ -47,7 +47,7 @@ function _ln(options, source, dest) {
   if (options.symlink) {
     fs.symlinkSync(source, dest, os.platform() === "win32" ? "junction" : null);
```
Comment (BYK) [inline src/ln.js]: We should only use `"junction"` if we know the source is a directory. Gonna handle this separately since we never test symlinking for directories.

**Comment by BYK** [comment]
This commit is mostly "if Windows, skip these tests" but unfortunately Windows is not POSIX compatible so certain things don't even work on Windows (`chmod` for instance). I'll try to make symlinking work properly first and then see if I can get `chmod` working.

Tests for `test -L` is also tricky because `git` on Windows checks symlinks as normal files with symlinked filename as the content making it impossible to use the links in `resources` directory on Windows. Once/if `ln -s` is fixed, we may use that to create links and then test them.

File: src/ln.js (hunk 1 above)
Comment (nfischer) [inline src/ln.js]: Looks like the docs agree :+1:

File: test/test.js [hunk 3]
```diff
@@ -63,24 +64,27 @@ assert.equal(shell.error(), null);
...
-assert.equal(result, true);//true
-
-var result = shell.test('-L', 'resources/badlink');
-assert.equal(shell.error(), null);
-assert.equal(result, true);//true
-
-var result = shell.test('-L', 'resources/404');
-assert.equal(shell.error(), null);
-assert.equal(result, false);//false
+// Windows is weird with links so skip these tests
```
Comment (nfischer) [inline test/test.js]: Is there no way to support links on Windows? If we can't find a way to make `ln` behave properly on Windows, then we'll need to document it as not running on Windows. It'd be preferable if we could fix the behavior and get at least some links to work.

File: test/pushd.js [hunk 4]
```diff
@@ -190,31 +190,31 @@ assert.equal(process.cwd(), trail[0]);
...
 assert.equal(process.cwd(), trail[0]);
 
 trail = shell.pushd();
 assert.equal(shell.error(), null);
 assert.equal(trail.length, 3);
 assert.equal(trail[0], root);
-assert.equal(path.relative(root, trail[1]), 'resources/pushd/a');
-assert.equal(path.relative(root, trail[2]), 'resources/pushd');
+assert.equal(path.relative(root, trail[1]), path.join('resources', 'pushd', 'a'));
+assert.equal(path.relative(root, trail[2]), path.join('resources', 'pushd'));
```
Comment (nfischer) [inline test/pushd.js]: :+1: nice!

File: test/cp.js [hunk 5]
```diff
@@ -139,11 +140,14 @@ shell.cp('-r', 'resources/cp/dir_a', 'tmp/dest');
...
 assert.equal(fs.existsSync('tmp/dest/z'), true);
 
-//preserve mode bits
-shell.rm('-rf', 'tmp/*');
-var execBit = parseInt('001', 8);
-assert.equal(fs.statSync('resources/cp-mode-bits/executable').mode & execBit, execBit);
-shell.cp('resources/cp-mode-bits/executable', 'tmp/executable');
-assert.equal(fs.statSync('resources/cp-mode-bits/executable').mode, fs.statSync('tmp/executable').mode);
+// On Windows, permission bits are quite different so skip those tests for now
+if (common.platform !== 'win') {
```
Comment (nfischer) [inline test/cp.js]: What's different about permissions on Windows? I know executable permissions are a bit different, but do read/write permissions work as expected?

File: test/test.js (hunk 3 above)
Comment (BYK) [inline test/test.js]: Hey, see my other comments - especially https://github.com/shelljs/shelljs/pull/297#discussion_r50105148

This is a bug, long existed in shelljs but it is large enough to deserve a separate bug and PR IMO.

File: test/cp.js (hunk 5 above)
Comment (BYK) [inline test/cp.js]: >What's different about permissions on Windows? I know executable permissions are a bit different, but do read/write permissions work as expected?

Please see the following:
- https://github.com/nodejs/node-v0.x-archive/issues/4812
- http://stackoverflow.com/a/23330010/90297

File: test/test.js (hunk 3 above)
Comment (nfischer) [inline test/test.js]: I agree, if you could open a github issue for the bug, that would be nice to have documented. And if we can get that fixed, even better!

Comment (BYK) [inline test/test.js]: Done: #301.

I'm willing to take this on. Shouldn't be too hard.

File: test/cp.js (hunk 5 above)
Comment (nfischer) [inline test/cp.js]: I see. So it sounds like something we should document as not being well supported on Windows. If we could update the docs to specify which features of chmod work on Windows, that'd be great.

Comment (BYK) [inline test/cp.js]: Agreed and ticketed: #302

File: test/test.js (hunk 3 above)
Comment (nfischer) [inline test/test.js]: Awesome! :+1:

**Comment by nfischer** [comment]
@BYK looks like there's some merge conflicts. Could you resolve?

@ariporad Do you think we should merge, or wait until `chmod` and `ln` have their Windows-incompatibility documented? This blocks #299, which is a priority.

**Comment by mtscout6** [comment]
I'd advocate for merging #299 first to ensure these fixed tests work in AppVeyor before merging.

**Comment by BYK** [comment]
@nfischer done

**Comment by nfischer** [comment]
@BYK could you rebase off master one more time? That will make sure AppVeyor runs checks on the code

**Comment by BYK** [comment]
@nfischer done :)

**Comment by nfischer** [comment]
@BYK could you modify `test/shjs.js`? I think we need to change:

> ```Javascript
>   return shell.exec(path.resolve(__dirname, '../bin/shjs') +
>                     ' ' +
>                     path.resolve(__dirname, 'resources', 'shjs', name), { silent: true });
> ```

into:

> ```Javascript
>   return shell.exec((process.platform === 'win32' ? 'node ' : '') + // call by path for unix, call with 'node' for Windows
>                     path.resolve(__dirname, '../bin/shjs') +
>                     ' ' +
>                     path.resolve(__dirname, 'resources', 'shjs', name), { silent: true });
> ```

I think the issue is that Windows can't call the .js file directly, while we expect OSX/Linux to be able to.

**Comment by nfischer** [comment]
@BYK Also, awesome job fixing the other tests! It's great to finally have (almost) all the tests passing on Windows.

**Comment by nfischer** [comment]
@BYK or you can just rebase off of the branch in #315 (or off master if it gets merged). This contains the fix I wrote above for the `shjs` test.

**Comment by nfischer** [comment]
I'm going to go ahead and merge this, since I tested it in a separate branch, and I tested it rebased off master and it passes appveyor CI now that #315 is merged :+1:

**Comment by nfischer** [comment]
@BYK Thanks again for all your help! This rocks!

**Comment by BYK** [comment]
@nfischer - glad I could help. I'm planning to help with other Windows issues too. Just don't have a much time. May be over the weekend :)
