### PR TITLE
Fix cp overwriting identical files

### LINKED ISSUE #678: *CRITICAL data loss* shell.cp() Content of file is erased when trying to copy it to the folder it already belongs to
### Node version (or tell us if you're using electron or some other framework):
7.5.0
### ShellJS version (the most recent version/Github branch you see the bug on):
0.7.5
### Operating system:
Mac OS X
### Description of the bug:
If you try to copy a file to the folder it already belongs to, the content of the file is erased.
### Example ShellJS command to reproduce the error:

```bash
echo "blah" > /home/test
```

```javascript
shell.cp('/home/test', '/home')
```

```bash
cat /home/test
```

`/home/test` is now empty.

### PR DESCRIPTION
**Pull request by freitagbr**
If `cp` is passed a destination that is location of a source file, in effect, copying a file to itself, the source file will become empty. This prevents this situation form happening by verifying that the destination is a different location than the source.

Fixes #678

### CODE REVIEW

**Comment by freitagbr** [comment]
Same bug from #673 is affecting the windows tests here. Let's see if we can implement a fix.

File: src/cp.js [hunk 1]
```diff
@@ -260,9 +261,25 @@ function _cp(options, sources, dest) {
         return; // skip file
       }
 
+      if (path.relative(src, thisDest) === '') {
+        // a file cannot be copied to itself, but we want to continue copying other files,
+        // so save the error for later
+        identicalFiles.push("'" + thisDest + "' and '" + src + "' are the same file");
```
Comment (freitagbr) [inline src/cp.js]: Will this still set the `result.stderr`? And `shell.error()` to `true`?

File: test/cp.js [hunk 2]
```diff
@@ -653,3 +653,21 @@ test('recursive, with a non-normalized path', t => {
...
+  t.is(result.stderr, "cp: 'resources/file1' and 'resources/file1' are the same file");
+});
+
+test('copy mutliple files to same location', t => {
+  const result = shell.cp('resources/file1', 'resources/file2', 'resources');
+  t.truthy(shell.error());
+  t.is(result.code, 1);
+  t.is(
+    result.stderr,
+    "cp: 'resources/file1' and 'resources/file1' are the same file\n" +
```
Comment (freitagbr) [inline test/cp.js]: Issue #6? Or issue #681?

Comment (freitagbr) [inline test/cp.js]: This test was fixed by rebasing off of master.

File: test/cp.js [hunk 3]
```diff
@@ -653,3 +653,21 @@ test('recursive, with a non-normalized path', t => {
   t.falsy(result.stderr);
   t.is(result.code, 0);
 });
+
+test('copy file to same location', t => {
+  const result = shell.cp('resources/file1', 'resources');
```
Comment (freitagbr) [inline test/cp.js]: Yes, so I added a test for this.

File: src/cp.js (hunk 1 above)
Comment (nfischer) [inline src/cp.js]: It sets `result.stderr` to the error output (it's a `+=` operation, so it all collects up). `shell.error()` is some truthy value (it's currently the same string as `result.stderr`, but this is no longer guaranteed as part of the API and it may later change to an error code).

File: test/cp.js (hunk 2 above)
Comment (nfischer) [inline test/cp.js]: I meant 681. But this comment can be ignored now 😄

Comment (freitagbr) [inline test/cp.js]: I figured. Once this is approved it should be good to merge.
