### PR TITLE
Fix cp to match unix behavior

### LINKED ISSUE #256: cp and rename directory with -r doesn't match unix behavior
As shown below, if I do `cp -r a b` with shelljs where `a` is a directory and `b` doesn't exist, shelljs creates `b/a` directories and the copies the contents of `a` into `b/a`.  Instead, like in a unix shell, it should create `b` directory and copy the contents of `a` into `b`.

```
> mkdir a
> touch a/file.txt
> node
> require('shelljs/global')
{}
> cp('-r', 'a', 'b');
undefined
> 
(To exit, press ^C again or type .exit)
> 
> ls b/
a
> rm -rvf b
b/a/file.txt
b/a
b/
> cp -rvp a b
a -> b
a/file.txt -> b/file.txt
```

### PR DESCRIPTION
**Pull request by freitagbr**
Fixes #256, #101.

### CODE REVIEW

**Comment by nfischer** [comment]
It might be helpful to add unit tests for this behavior. When I ran a quick test, it seemed to work as expected.

**Comment by nfischer** [comment]
@freitagbr Could you rebase off master?

**Comment by freitagbr** [comment]
@nfischer Done.

**Comment by nfischer** [comment]
Looks like some of the tests are still failing. If we could get these fixed (or have the tests adjusted, if appropriate), that'd be good

File: test/cp.js [hunk 1]
```diff
@@ -125,17 +125,23 @@ assert.equal(shell.cat('resources/cp/dir_a/z'), shell.cat('tmp/cp/dir_a/z')); //
 
 //recursive, creates dest dir since it's only one level deep (see Github issue #44)
 shell.rm('-rf', 'tmp/*');
-shell.cp('-r', 'resources/issue44/*', 'tmp/dir2');
+shell.cp('-r', 'resources/issue44', 'tmp/dir2');
```
Comment (nfischer) [inline test/cp.js]: Should these test cases be changed? What was wrong with the previous behavior?

File: test/cp.js [hunk 2]
```diff
@@ -125,17 +125,23 @@ assert.equal(shell.cat('resources/cp/dir_a/z'), shell.cat('tmp/cp/dir_a/z')); //
...
 assert.equal(shell.error(), null);
 assert.equal(shell.ls('-R', 'resources/issue44') + '', shell.ls('-R', 'tmp/dir2') + '');
 assert.equal(shell.cat('resources/issue44/main.js'), shell.cat('tmp/dir2/main.js'));
 
 //recursive, does *not* create dest dir since it's too deep (see Github issue #44)
 shell.rm('-rf', 'tmp/*');
-shell.cp('-r', 'resources/issue44/*', 'tmp/dir2/dir3');
+shell.cp('-r', 'resources/issue44', 'tmp/dir2/dir3');
```
Comment (nfischer) [inline test/cp.js]: Same question applies here

File: test/cp.js (hunk 1 above)
Comment (freitagbr) [inline test/cp.js]: In \*nix, `cp -r resources/issue44/* tmp/dir2` is not valid. If there is only one file in `resources/issue44`, it will be copied into `tmp` and be renamed `dir2`. If there is more than one file in `resources/issue44`, the command will fail.

The intention here is to copy all of the files in `resources/issue44` to `tmp/dir2`, where `dir2` will be created. This is achieved with the new command (and in *nix as well).

File: test/cp.js (hunk 2 above)
Comment (freitagbr) [inline test/cp.js]: Again, `cp -r resources/issue44/* tmp/dir2/dir3` is not valid.

File: test/cp.js (hunk 1 above)
Comment (nfischer) [inline test/cp.js]: Awesome explanation! The logic sounds right to me. It sounds like this is indeed a bug in the test. Thanks for fixing!

**Comment by nfischer** [comment]
LGTM! @ariporad

File: test/cp.js (hunk 1 above)
Comment (freitagbr) [inline test/cp.js]: Definitely!
