### PR TITLE
fix: allow non-normalized paths as input to mkdir

### LINKED ISSUE #634: mkdir fails with non-normalized path
### Example ShellJS command to reproduce the error:

```javascript
shelljs = require('shelljs');
shelljs.mkdir('-p', 'asdf/./');
```

Expected result is that no error should be thrown and certainly the process should not terminate.  `'-p'` flag should not fail for any existing path or part of path.

### PR DESCRIPTION
**Pull request by nfischer**
Adds tests to make sure that non-normalized paths (i.e. path/to/./dir) are
valid for a few commands, including mkdir() which previously failed when given
the -p flag.

Fixes #634

### CODE REVIEW

File: src/mkdir.js [hunk 1]
```diff
@@ -75,7 +75,7 @@ function _mkdir(options, dirs) {
 
     try {
       if (options.fullpath) {
-        mkdirSyncRecursive(dir);
+        mkdirSyncRecursive(path.resolve(dir));
```
Comment (freitagbr) [inline src/mkdir.js]: It seems like `fs.mkdirSync` normalizes the path passed to it anyway. Is that why `path.resolve` is not needed below?

Comment (nfischer) [inline src/mkdir.js]: Yes, that's correct.

It's needed here because, for each recursive call, we process another piece of the path. This can lead us to processing something that isn't valid for `mkdir`, like `.` or `..`. It can also lead us to processing the same directory twice (ex. `foo/../foo/`) which also isn't valid.

**Comment by nfischer** [comment]
@freitagbr LGTY?

**Comment by freitagbr** [comment]
Yes, LGTM.
