### PR TITLE
Fix common.expand error

### LINKED ISSUE #664: Passing empty string to cp throws internal error
### Node version (or tell us if you're using electron or some other framework):
v6.8.0
### ShellJS version (the most recent version/Github branch you see the bug on):
0.7.6
### Operating system:
Mac OS X
### Description of the bug:
Passing empty string to `cp` command throws an internal error.  Would be much easier to deal with an exception or error return.

```
ShellJS: internal error
Error: must provide pattern
    at new GlobSync (node_modules/glob/sync.js:31:11)
...
   at node_modules/shelljs/src/common.js:246:22
```

### Example ShellJS command to reproduce the error:

```javascript
shelljs.cp('', 'dest');
```

### PR DESCRIPTION
**Pull request by freitagbr**
Fixes #664

### CODE REVIEW

File: test/common.js [hunk 1]
```diff
@@ -170,6 +170,24 @@ test('broken links still expand', t => {
...
+
+test('empty string', t => {
+  const result = common.expand(['']);
+  t.falsy(shell.error());
+  t.deepEqual(result, ['']);
+});
+
+test('non-string', t => {
+  const result = common.expand([5]);
+  t.falsy(shell.error());
```
Comment (nfischer) [inline test/common.js]: No need to check `shell.error()`, it's never set by this function (it's internal). Maybe just file a bug to clean up these tests later.
